particle_system = part_system_create_layer("Instances", 0)

particle_type_Hit = part_type_create()
part_type_sprite(particle_type_Hit, spr_explosion_particle, 0,0,0)
part_type_size(particle_type_Hit, 1.5, 2, 0.1, 0)
part_type_life(particle_type_Hit, 5, 15)
part_type_alpha3(particle_type_Hit, 1, 0.6, 0.2)
part_type_orientation(particle_type_Hit, 0, 359, 0,0,0)

particle_type_player_spark = part_type_create()
part_type_sprite(particle_type_player_spark, spr_spark_player, 0,0,0)
part_type_size(particle_type_player_spark, 1.5, 2, 0.1, 0)
part_type_life(particle_type_player_spark, 5, 15)
part_type_alpha3(particle_type_player_spark, 1, 0.6, 0.2)
part_type_orientation(particle_type_player_spark, 0, 359, 0,0,0)


particle_type_Spark = part_type_create()
part_type_sprite(particle_type_Spark, spr_spark, 0,0,0)
part_type_size(particle_type_Spark, 0.8, 1.4, -0.01, 0)
part_type_life(particle_type_Spark, 25, 30)
part_type_alpha3(particle_type_Spark, 1, 0.8, 0.1)
part_type_orientation(particle_type_Spark, 0, 359, 0,0,0)
part_type_speed(particle_type_Spark, 2, 4, -0.1, 0)
part_type_direction(particle_type_Spark, 0, 359, 0, 0)
part_type_color3(particle_type_Spark, 45823, 829418, 952788)

particle_type_Hit_Prime = part_type_create()
part_type_sprite(particle_type_Hit_Prime, spr_explosion_particle_prime, 0,0,0)
part_type_size(particle_type_Hit_Prime, 1.5, 2, 0.1, 0)
part_type_life(particle_type_Hit_Prime, 5, 15)
part_type_alpha3(particle_type_Hit_Prime, 1, 0.6, 0.2)
part_type_orientation(particle_type_Hit_Prime, 0, 359, 0,0,0)

particle_type_Spark_Prime = part_type_create()
part_type_sprite(particle_type_Spark_Prime, spr_spark_prime, 0,0,0)
part_type_size(particle_type_Spark_Prime, 0.8, 1.4, -0.01, 0)
part_type_life(particle_type_Spark_Prime, 25, 30)
part_type_alpha3(particle_type_Spark_Prime, 1, 0.8, 0.1)
part_type_orientation(particle_type_Spark_Prime, 0, 359, 0,0,0)
part_type_speed(particle_type_Spark_Prime, 2, 4, -0.1, 0)
part_type_direction(particle_type_Spark_Prime, 0, 359, 0, 0)
